language: objective-c
osx_image: xcode9.3
branches:
  only:
    - develop
    - master
env:
  - DESTINATION="OS=11.3,name=iPhone 8" SCHEME="SimpleTabbar" SDK=iphonesimulator
before_install:
  - brew update
  - rvm install ruby-2.2.2
  - gem install xcpretty -N
script:
  - set -o pipefail
  - xcodebuild clean build -project SimpleTabbar.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
  - xcodebuild -project SimpleTabbar.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
